# Generated by Django 2.2.16 on 2022-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('posts', '0004_auto_20220715_1839'),
                ('posts', '0005_auto_20220719_0003'),
                ('posts', '0006_post_image'),
                ('posts', '0007_auto_20220720_1847')]

    dependencies = [
        ('posts', '0001_posts-group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'],
                     'verbose_name': 'Пост',
                     'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/',
                                    verbose_name='Картиинка'),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',),
                     'verbose_name': 'Пост',
                     'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/',
                                    verbose_name='Картинка'),
        ),
    ]
